### ISSUE TITLE
Error: ActiveState Basekit has stopped working

### ISSUE THREAD

**Issue by billy1624** [usnistgov/SFA#2]
Hi there, I'm running `STEP-File-Analyzer.exe` on `Windows Server 2016 Standard`, I got the following error message. Thanks!!

![image](https://user-images.githubusercontent.com/30400950/152970089-85cae7ad-6525-4f81-a67d-dce6c27c2858.png)

**Comment by billy1624** [comment]
Btw... the CLI doesn't work as well for some reason

<img width="978" alt="image" src="https://user-images.githubusercontent.com/30400950/152995070-67d5475b-9068-4ab7-a782-da9950202d8d.png">

**Comment by robert-lipman** [comment]
Hi Billy,  as far as I know the software cannot be run on Windows Server.  I'm not sure if that is the reason why the CLI also isn't working.

**Comment by billy1624** [comment]
Hey @robert-lipman, thanks for the prompt reply. Is it possible that I run the .tcl source code directly on Windows server?

**Comment by robert-lipman** [comment]
The problem is with running the IFCsvr toolkit on Windows Server and not the Tcl source code.  The source code worked given that you got the user interface to start.  I do not have access to the IFCsvr source code so it cannot be modified for Windows Server.  I also don't have access to Windows Server.

You can still run the Viewer part of the software by selecting View and Part Only in the user interface.  You won't be able to generate a spreadsheet which is dependent on IFCsvr.

To help me diagnose the problem a bit better can you send me a few more screenshots and information.  In the GUI version, go to Help > About.  There should be some information about System.  Please send that info.

Then go to the Spreadsheet tab and under Max Rows select 100000.  The do Help > About again.  There will be a lot more system variables.  Please send a screenshot of that information.

Hopefully some of this information will help me detect Windows Server and the software can respond appropriately.

**Comment by billy1624** [comment]
Thanks for the help!! @robert-lipman
